const ADD_TO_LIKE = 'ADD_TO_LIKE';
const REMOVE_FROM_LIKE = 'REMOVE_FROM_LIKE';
const CLEAR_LIKE = 'CLEAR_LIKE';

const TOGGLE_THEME = 'TOGGLE_THEME';

export {
   ADD_TO_LIKE,
   REMOVE_FROM_LIKE,
   CLEAR_LIKE,
   TOGGLE_THEME
}